# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode9.3
language: swift
# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
script:
- pod setup
- pod update --project-directory=Example
- pod install --project-directory=Example 
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/HSCenterSlider.xcworkspace -scheme HSCenterSlider-Example -sdk iphonesimulator11.3 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod setup
- pod lib lint --swift-version=4.0
